import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { CartProvider } from "@/context/cartContext";
import { UserProvider } from "@/context/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} flex flex-col min-h-screen`}>
    <UserProvider>
    <CartProvider>
      <Navbar />
      <main className="flex-grow bg-white font-serif">{children}</main>
      <Footer />
      </CartProvider>
      </UserProvider>
    </body>
  </html>
);
}
